services:
  - type: web
    name: chatcode
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: APP_SECRET
        generateValue: true
      - key: BASE_URL
        value: https://chatcode.su
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
    disk:
      name: chatcode-disk
      mountPath: /opt/render/project/src
      sizeGB: 1